name: Backmerge master --> staging

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  backmerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Create Pull Request
        run: |
          gh pr create --title="Backmerge" --body="" --base="staging" --head="master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
